# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-utilities-rel-1-0-0
  namespace: processor
  labels:
    app: nats-utilities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-utilities
  template:
    metadata:
      name: nats-utilities-rel-1-0-0
      labels:
        app: nats-utilities
      annotations:
        prometheus.io.scrape: 'false'
    spec:
      containers:
        - name: nats-utilities-rel-1-0-0
          image: example.io/nats-utilities-rel-1-0-0:1.0.0
          ports:
            - name: http	            
              protocol: TCP
              containerPort: 3000	
              hostPort: 3000
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: frmpullsecret
      schedulerName: default-scheduler
      enableServiceLinks: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
